### ISSUE TITLE
Ошибка при запросе замечаний.

### ISSUE THREAD

**Issue by 1cgh** [theshadowco/sonar-helper#3]
Первое использование на местном сонаре) Что-то пошло не так:
```
C:\GIT>sonar-helper issue-resolver --cfg-file c:\GIT\1cgh\example.cfg-file.json
sonar-helper v1.1.1
ИНФОРМАЦИЯ - Получение информации о проектах
ИНФОРМАЦИЯ - Получение информации о родительском проекте
ИНФОРМАЦИЯ - Получение закрываемых замечаний из родительского проекта
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\sonar-helper\src\
Модули\Сонар.os / Ошибка в строке: 268 / Код ответа: 400
Ответ: {"errors":[{"msg":"Can return only the first 10000 results. 10500th resul
t asked."}]}}
```

**Comment by 1cgh** [comment]
Да. Есть ограничение на выдачу 10000 ишузов через web api.
Т.е. надо менять подход и как-то дробить выборку.

**Comment by theshadowco** [comment]
Да, натыкался на данное ограничение, для чего и городил фильтрацию. 
Значит надо придумать алгоритм как еще подробить, но пока все варианты также могут приводить к этому ограничению.

**Comment by 1cgh** [comment]
@theshadowco попробую через api/components/tree получать дерево каталогов по проекту и дальше уже в цикле замечания по каталогам собирать. при этом делать это только если total по "простому" поиску больше 10000.
аналогично если по какому-то каталогу total больше 10000, то до файлов дробить.
а вот что делать если в файле больше 10к замечаний - я не знаю))

**Comment by bia-tech** [comment]
@1cgh 
Я как раз на этом сейчас и стою - есть модули с 30к+ строк и по 15к+ ошибок :(

**Comment by 1cgh** [comment]
@bia-tech сегодня доделаю и PR закину.
я делаю так:
цикл по статусам оставляем
по статусу получаем первую страницу ишузов по проекту
если там тотал больше 10000, то сразу ясно, что так мы их все не соберем
получаем каталоги по проекту и начинаем собирать в цикле по каталогам
для каталога аналогично смотрим тотал, если больше 10000, то для этого каталога получаем список модулей и собираем замечания в цикле по модулям

ну вот, а если уже в модуле будет больше 10000 замечаний, то тогда упадет. но это какой-то очень плохой модуль должен быть)

**Comment by theshadowco** [comment]
@1cgh 

Супер!

**Comment by 1cgh** [comment]
а по одному модулю, если в нем больше 10к, то можно по идее вытягивать в разрезе правил
в issues/search есть параметр rules

**Comment by 1cgh** [comment]
модуль = файл в терминологии сонара. извиняюсь, а то вдруг путаницу внес)

**Comment by 1cgh** [comment]
чета я где-то накосячил, разбираюсь где, или что-то в API не учел: сумма ишузов по каталогам не совпадает с тотал по проекту)

**Comment by theshadowco** [comment]
Давай что есть - доделаю, идею понял

ср, 20 марта 2019 г., 21:53 Nenashev Anatoliy <notifications@github.com>:

**Comment by theshadowco** [comment]
Реализация в develop.

@1cgh Посмотри, если норм - выпущу релиз

**Comment by theshadowco** [comment]
```
ОТЛАДКА - Для проекта `bukhgalteriiapredpriiatiia_190:master` найдено замечний: `225919`
ИНФОРМАЦИЯ - Для проекта `bukhgalteriiapredpriiatiia:master` будет закрыто замечаний: `110947`
```

**Comment by 1cgh** [comment]
@theshadowco сейчас попробую. у меня просто получалось, что количество найденных замечаний по каталогам не совпадало с фактическим в сонаре (а total, который issues/search только проекта, совпадал)
вот у тебя 

> ОТЛАДКА - Для проекта `bukhgalteriiapredpriiatiia_190:master` найдено замечний: `225919`

их столько всего и есть по этому проекту?

**Comment by theshadowco** [comment]
@1cgh 

Да, совпало. Проверял через  postman

**Comment by theshadowco** [comment]
@1cgh 

обрати внимание, я каталоги через tree достал, а не через search

**Comment by 1cgh** [comment]
@theshadowco
я проверяю по собранным замечаниям родительского проекта вот так:
```
		ВсегоЗамечаний = 0;
		Для каждого Замечание Из ЗамечанияРодительскогоПроекта Цикл
			ВсегоЗамечаний = ВсегоЗамечаний + Замечание.Значение.Ошибки.Количество();
		КонецЦикла;

```
и их должно быть, например, 37577, а получается 24732

**Comment by 1cgh** [comment]
@theshadowco и это я и на твоей реализации, и на своей проверил.
и вот либо я неправильно считаю сумму замечаний, собранных в соответствие, либо одно из двух

**Comment by 1cgh** [comment]
такс, возможно, это из-за того, hash ошибок по одной строке, но разным правилам - одинаковый, т.е. проблема в Функция ПолучитьХэшЗамечания(ОписаниеОшибки, ПутьКФайлу)

**Comment by theshadowco** [comment]
@1cgh 

Добавил правило и модуль к хэшу

**Comment by 1cgh** [comment]
@theshadowco стало 30617 в родительском получать
допускаю, что есть правила, где замечания получат одинаковый хэш, типа bsl:UnusedFormAttribute
поковыряю, возможно, это всё они и есть

**Comment by theshadowco** [comment]
@1cgh 

наверное стоит вернуть мой алгоритм расчета хэша, а не сонаровский.

**Comment by 1cgh** [comment]
@theshadowco можно. но все равно останутся замечания с одинаковым хешем и по твоему алгоритму. может, оно и пофиг, лишь бы в дочерних корректно отрабатывал поиск всех замечаний с тем же хешем.

и еще надо найти и почитать как точно хеш сонара считается. т.е. что в нем учитывается, какой контекст
просто в твоём алгоритме есть проблема, что при малейшей доработке в дочернем проекте относительно родительского строки сдвинутся, и хеш из-за нового textrange будет другим, совпадения не будет, замечание не закроется

**Comment by theshadowco** [comment]
угу 

с хэшами сонара дубли на правиле bsl:BooleanLiteral
с моим алгоритмом дубли на bsl:PunctuatorsIndent

**Comment by theshadowco** [comment]
![image](https://user-images.githubusercontent.com/9591731/54757295-fbce0180-4bfa-11e9-8136-e4e6177e4606.png)

**Comment by theshadowco** [comment]
вот еще веселей

![image](https://user-images.githubusercontent.com/9591731/54757676-c7a71080-4bfb-11e9-9e3b-95e220413f54.png)

**Comment by 1cgh** [comment]
@theshadowco
key я тоже не знаю, как назначается, и можно ли вообще на него рассчитывать)

а с замечаниями, которые должны по идее иметь startOffset и endOffset, ничего не сделать, если их несколько по одной строке, так как это не реализовано в плагине. и 2 замечания по недостающим пробелам в разных местах одной строки будут иметь одинаковые
hash и значения в textRange

**Comment by theshadowco** [comment]
@1cgh 

ключ формируется автоинкрементом, я посмотрел на соседнем проекте. 

В итоге получается, что если хэши одинаковые, то закрыть можем один какой-то, но при повторном прогоне закроется и второй :(.

Тут либо договариваться с вендором, либо согласиться с такой особенностью, либо не закрывать такие таски.

**Comment by 1cgh** [comment]
т.е. надо прийти к тому, чтобы в дочернем проекте не были закрыты лишние замечания, добавленные уже плюсом к тем, что привнесены из родительского

**Comment by 1cgh** [comment]
ну в общем я предлагаю:

1. Хеш формировать из имя файла + имя правила + (hash сонара где он есть или hash из полей textRange, где нет hash сонара)
2. Считать количество замечаний в родительском проекте по одинаковому хешу
3. При закрытии в дочернем проекте аналогично подсчитывать количество замечаний по хешу
4. Закрывать замечание только если количество совпадает. При этом должны быть закрыты все замечания, а не первое найденное.

**Comment by 1cgh** [comment]
т.е., например, если в родительском проекте есть 3 замечания в файле с одним рассчитанным хешем, то в дочернем их должно быть тоже 3. если меньше или больше, то пропускаем. если тоже 3, то закрываем все 3

**Comment by theshadowco** [comment]
есть нюанс - а если одно из замечаний в родительском исправлено, какое исправлять в дочернем

**Comment by 1cgh** [comment]
> есть нюанс - а если одно из замечаний в родительском исправлено, какое исправлять в дочернем

никакое. т.е. закрываем при точном совпадении.
да, могут быть ситуации, когда в пределах одного хеша в дочернем было исправлено одно замечание из родительского и добавлено своё, но это, я думаю, допустимо

**Comment by theshadowco** [comment]
не совсем: реализована фильтрация по статусам замечаний, в родительском при фильтрации получается 1 закрыто, сколько не закрытых - не известно. В дочернем тоже одно не закрыто, но какое - не известно. 

Таким образом все равно закроем не то.

Либо, из родительского читать ВСЕ, считать сколько всего и сколько из них будем закрывать. В дочернем считаем количество ВСЕХ, сравниваем. Если количество всего равны, то закрывам столько, чтобы уровнять количество закрытых и не закрытых в двух проектах.

**Comment by 1cgh** [comment]
да, согласен. совсем забыл про статусы

**Comment by theshadowco** [comment]
Тогда предлагаю остановиться на следующем:
кейс 1 - есть оганичение по статусам (т.е. выбраны не все статусы из списка возможных)
 - выбираем замечания в соответствии со статусами из родительского
 - выбираем по компоненту замечания из дочернего
 - находим по хэшу подходящие замечания в дочернем проекте и считаем их количество без ограничений по статусу
 - если количество замечаний в дочернем 1 - тогда закрываем открытые, иначе - пропускаем

кейс 2 - ограничений по статусам нет (т.е. выбраны все статусы из списка возможных)
 - выбираем замечания в из родительского и считаем их количество
 - выбираем по компоненту замечания из дочернего
 - находим по хэшу подходящие замечания в дочернем проекте и считаем их количество без ограничений по статусу
 - если количество замечаний в дочернем и в родительском равно - тогда закрываем открытые, иначе - пропускаем

**Comment by theshadowco** [comment]
Либо такой вариант
 - выбираем нужные (с учетом статусов) замечания из родительского проекта, сохраняем в разрезе модуля и правила
 - по каждому модулю и правилу (если фильтр по статусам присутствует) делаем запрос и получаем количество замечаний, у которых хэш совпадает с выбранными
 - для дочерних проектов находим замечания по модулю и правилу
 - если их количество и хэши совпадают с родительскими, то сравниваем количество закрытых с родительским (т.е. если в дочернем закрытых мешьше - дозакроем, если больше, оставим как есть)

**Comment by theshadowco** [comment]
Реализовал по последнему варианту

**Comment by artbear** [comment]
@theshadowco @1cgh Вы новый релиз 1.16 пульского плагина получили, верно?
посмотрите новые возможности ускорения анализа и отключения кода на поддержке / включения кода из своих подсистем.

Возможно, вам текущие проблемы удастся решить, не используя родительские проекты :)

**Comment by bia-tech** [comment]
А плагин разве стал поддерживать java? Я данный скрипт вообще не для 1с делал :)

Скачайте Outlook для Android<https://aka.ms/ghei36>




On Mon, Mar 25, 2019 at 3:38 PM +0300, "Artur Ayukhanov" <notifications@github.com<mailto:notifications@github.com>> wrote:


@theshadowco<https://github.com/theshadowco> @1cgh<https://github.com/1cgh> Вы новый релиз 1.16 пульского плагина получили, верно?
посмотрите новые возможности ускорения анализа и отключения кода на поддержке / включения кода из своих подсистем.

Возможно, вам текущие проблемы удастся решить, не используя родительские проекты :)

**Comment by 1cgh** [comment]
@artbear пока, увы, только увеличение времени анализа наблюдаем при прочих равных между 1.15 и 1.16
