### ISSUE TITLE
Путь к сонару отличного от корневого

### ISSUE THREAD

**Issue by Kirill** [theshadowco/sonar-helper#8]
Для использования сонара отличного от установки в корневой адрес сервера необходимо проводить разделение адрес сервера на сам сервер и начальный URI. Например, http://10.10.10.33/sonarqube, тогда адрес сервера 10.10.10.33, а префикс /sonarqube/api/, а не просто /api/

**Comment by theshadowco** [comment]
@Kirill 

Сорри за долгий ответ

Не могу проверить у себя, а если в параметрах АдресСервера передать "http://10.10.10.33/sonarqube" разве не будет работать?

**Comment by Kirill** [comment]
К сожалению, нет.
Пока жестко отредактировал строку https://github.com/theshadowco/sonar-helper/blob/96500f992dd9f13870e8ac58bbce0a6416a5e4c7/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%A1%D0%BE%D0%BD%D0%B0%D1%80.os#L463
Как просто задать настройку, чтобы не сломался сам функционал - не придумал.

**Comment by theshadowco** [comment]
Попробуй версию https://github.com/theshadowco/sonar-helper/releases/tag/1.2.1

**Comment by Kirill** [comment]
Спасибо. Сработало.
